// src/lib/components/MeetingV2/MeetingNameField.svelte
<script lang="ts">
  import { onMount } from "svelte";

  import { DEFAULT_MEETING_NAME, meetingName } from "$lib/stores/meetingSetupStores";
  import EditNoteIcon from "~icons/material-symbols/edit-note";

  /* Reset to the default meeting name*/
  onMount(() => {
    $meetingName = DEFAULT_MEETING_NAME;
  });

  const onFocus = (e: Event) => {
    (e.target as HTMLInputElement).select();
  };
  const onSelect = (e: Event) => {
    (e.target as HTMLInputElement).select();
  };
</script>

<div>
  <div class="flex flex-row gap-x-1 pb-1 text-slate-medium">
    <EditNoteIcon />
    <p class="text-sm font-bold uppercase">Meeting Name</p>
  </div>

  <div class="flex w-[80%] flex-row items-center gap-x-4 text-lg text-gray-500">
    <input
      type="text"
      class="flex-center w-full appearance-none rounded-none border-x-0 border-t-0 border-gray-base p-1 placeholder:text-gray-base focus:outline-none focus:ring-0"
      placeholder="ex: Science Library LAN Party"
      on:focus={onFocus}
      on:select={onSelect}
      bind:value={$meetingName}
    />
  </div>
</div>

// src/components/creation/fields/meeting-name-field.tsx
"use client";

import React, { Dispatch, SetStateAction, useEffect, useRef } from "react";

const DEFAULT_MEETING_NAME = "";

interface MeetingNameFieldProps {
    meetingName: string;
    setMeetingName: Dispatch<SetStateAction<string>>;
}

export function MeetingNameField({
    meetingName,
    setMeetingName,
}: MeetingNameFieldProps) {
    const inputRef = useRef<HTMLInputElement>(null);

    useEffect(() => {
        setMeetingName(DEFAULT_MEETING_NAME);

        if (inputRef.current) {
            inputRef.current.focus();
        }
    }, [setMeetingName]);

    const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        setMeetingName(e.target.value);
    };

    return (
        <div className="flex flex-row items-center gap-x-4 text-lg text-gray-500">
            <input
                type="text"
                className="flex-center border-gray-base placeholder:text-gray-base w-full appearance-none rounded-none border-x-0 border-t-0 p-1 text-2xl font-light focus:outline-none focus:ring-0 md:text-3xl"
                placeholder="Meeting Name"
                value={meetingName}
                onChange={handleChange}
                ref={inputRef}
            />
        </div>
    );
}
