// src/lib/components/meetingSetup/MeetingNameField.svelte
<script lang="ts">
  import { onMount } from "svelte";

  import { DEFAULT_MEETING_NAME, meetingName } from "$lib/stores/meetingSetupStores";

  /* Reset to the default meeting name*/
  onMount(() => {
    $meetingName = DEFAULT_MEETING_NAME;
  });

  const onFocus = (e: Event) => {
    (e.target as HTMLInputElement).select();
  };
  const onSelect = (e: Event) => {
    (e.target as HTMLInputElement).select();
  };
</script>

<div id="meeting-name-input-container" class="mx-auto mb-3 h-12 w-80">
  <input
    type="text"
    alt="meeting name input"
    id="meeting-name-input"
    class="input h-full w-full rounded-lg text-center text-2xl text-zinc-500"
    on:focus={onFocus}
    on:select={onSelect}
    bind:value={$meetingName}
  />
</div>

// src/components/creation/fields/meeting-name-field.tsx
import React, { Dispatch, SetStateAction, useEffect, useRef } from "react";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";

const DEFAULT_MEETING_NAME = "";

interface MeetingNameFieldProps {
    meetingName: string;
    setMeetingName: Dispatch<SetStateAction<string>>;
}

export function MeetingNameField({
    meetingName,
    setMeetingName,
}: MeetingNameFieldProps) {
    const inputRef = useRef<HTMLInputElement>(null);

    useEffect(() => {
        setMeetingName(DEFAULT_MEETING_NAME);

        if (inputRef.current) {
            inputRef.current.focus();
        }
    }, [setMeetingName]);

    const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        setMeetingName(e.target.value);
    };

    return (
        <div className="flex flex-row items-center gap-x-4 text-lg text-gray-500">
            <Input
                type="text"
                className={cn(
                    "flex-center w-full appearance-none rounded-none border-x-0 border-t-0 border-gray-base p-1 text-2xl font-light placeholder:text-gray-base md:text-3xl",
                    "focus-visible:ring-0"
                )}
                placeholder="Meeting Name"
                value={meetingName}
                onChange={handleChange}
                ref={inputRef}
            />
        </div>
    );
}
