// src/components/creation/calendar/calendar.tsx
import React, { Dispatch, SetStateAction, useMemo, useState } from "react";
import { CalendarBody } from "@/components/creation/calendar/calendar-body";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { MONTHS, WEEKDAYS } from "@/lib/types/chrono";
import { ZotDate } from "@/lib/zotdate";
import { isDatePast } from "@/lib/creation/utils";

interface CalendarProps {
    selectedDays: ZotDate[];
    setSelectedDays: Dispatch<SetStateAction<ZotDate[]>>;
}

export function Calendar({ selectedDays, setSelectedDays }: CalendarProps) {
    const today = new Date();
    const [currentMonth, setCurrentMonth] = useState(today.getMonth());
    const [currentYear, setCurrentYear] = useState(today.getFullYear());

    const monthName = MONTHS[currentMonth];
    const calendarDays = useMemo(
        () => ZotDate.generateZotDates(currentMonth, currentYear, selectedDays),
        [currentMonth, currentYear, selectedDays]
    );

    const decrementMonth = () => {
        let newMonth = currentMonth - 1;
        let newYear = currentYear;

        if (newMonth < 0) {
            newMonth = 11;
            newYear -= 1;
        }

        setCurrentMonth(newMonth);
        setCurrentYear(newYear);
    };

    const incrementMonth = () => {
        let newMonth = currentMonth + 1;
        let newYear = currentYear;

        if (newMonth > 11) {
            newMonth = 0;
            newYear += 1;
        }

        setCurrentMonth(newMonth);
        setCurrentYear(newYear);
    };

    /**
     * Updates a range of dates based on a user selection
     * @param startDate the day that the user first initiated the date multiselect range
     * @param endDate the day that the user ended the date multiselect range
     */
    const updateSelectedRange = (
        startDate: ZotDate,
        endDate: ZotDate
    ): void => {
        const highlightedRange: Date[] = ZotDate.generateRange(
            startDate.day,
            endDate.day
        );

        setSelectedDays((alreadySelectedDays: ZotDate[]) => {
            let modifiedSelectedDays = [...alreadySelectedDays];

            highlightedRange.forEach((highlightedLocalDate: Date) => {
                const highlightedZotDate = new ZotDate(highlightedLocalDate);
                const foundSelectedDay = alreadySelectedDays.find(
                    (d) => d.compareTo(highlightedZotDate) === 0
                );

                // Remove any selected days if the multiselect initiated from an already selected day
                if (startDate.isSelected && foundSelectedDay) {
                    modifiedSelectedDays = modifiedSelectedDays.filter(
                        (d) => d.compareTo(foundSelectedDay) !== 0
                    );
                }

                // Add day to selected days if the multiselect did not initiate from an already selected day
                if (!startDate.isSelected && !foundSelectedDay) {
                    if (isDatePast(highlightedLocalDate)) return;
                    modifiedSelectedDays.push(
                        new ZotDate(
                            highlightedLocalDate,
                            undefined,
                            undefined,
                            true
                        )
                    );
                }
            });

            return modifiedSelectedDays;
        });
    };

    return (
        <div className="flex items-center justify-between rounded-xl border bg-gradient-to-l from-[#00A96E0D] to-[#377CFB0D] py-7 md:p-5">
            <Button
                onClick={decrementMonth}
                className="bg-transparent p-3 hover:bg-transparent md:pl-1"
            >
                <span className="text-3xl text-gray-500">&lsaquo;</span>
            </Button>

            <div className="md:px-4">
                <div className="flex flex-col pb-5">
                    <h3 className="text-left font-montserrat text-2xl font-semibold text-gray-dark md:text-3xl">
                        {monthName} {currentYear}
                    </h3>
                </div>

                <table className="w-full table-fixed p-3">
                    <thead>
                        <tr>
                            {WEEKDAYS.map((dayOfWeek) => (
                                <th
                                    className="px-0"
                                    key={dayOfWeek}
                                >
                                    <div>
                                        <p className="w-full text-center text-sm font-light uppercase text-slate-medium md:font-bold">
                                            {dayOfWeek}
                                        </p>
                                    </div>
                                    <Separator className="my-2 h-[2px] bg-slate-base" />
                                </th>
                            ))}
                        </tr>
                    </thead>

                    <CalendarBody
                        calendarDays={calendarDays}
                        currentMonth={currentMonth}
                        updateSelectedRange={updateSelectedRange}
                    />
                </table>
            </div>

            <Button
                onClick={incrementMonth}
                className="bg-transparent p-3 hover:bg-transparent"
            >
                <span className="text-3xl text-gray-500">&rsaquo;</span>
            </Button>
        </div>
    );
}

// src/lib/components/meetingSetup/Calendar/Calendar.svelte
<script lang="ts">
  import CalendarBody from "./CalendarBody.svelte";

  import { selectedDays } from "$lib/stores/meetingSetupStores";
  import { WEEKDAYS, MONTHS } from "$lib/types/chrono";
  import { ZotDate } from "$lib/utils/ZotDate";

  let today: Date = new Date();
  let currentMonth: number = today.getMonth();
  let currentYear: number = today.getFullYear();
  let calendarDays: ZotDate[][] = ZotDate.generateZotDates(
    currentMonth,
    currentYear,
    $selectedDays,
  );

  $: monthName = MONTHS[currentMonth];

  const updateCalendar = (): void => {
    calendarDays = ZotDate.generateZotDates(currentMonth, currentYear, $selectedDays);
  };
  const decrementMonth = (): void => {
    currentMonth--;
    if (currentMonth < 0) {
      currentMonth = 11;
      currentYear--;
    }

    updateCalendar();
  };

  const incrementMonth = (): void => {
    currentMonth++;
    if (currentMonth > 11) {
      currentMonth = 0;
      currentYear++;
    }

    updateCalendar();
  };
</script>

<p class="h3 text-center">{monthName} {currentYear}</p>
<div class="flex items-center justify-between overflow-x-auto pt-5">
  <button on:click={decrementMonth} class="p-3 pl-1">
    <span class="text-3xl text-gray-500">&lsaquo;</span>
  </button>
  <table class="w-full">
    <thead>
      <tr>
        {#each WEEKDAYS as dayOfWeek}
          <th>
            <div class="flex w-full justify-center">
              <p class="text-center text-base font-medium text-gray-800 dark:text-gray-100">
                {dayOfWeek}
              </p>
            </div>
          </th>
        {/each}
      </tr>
    </thead>
    <CalendarBody {calendarDays} {updateCalendar} {currentMonth} />
  </table>
  <button on:click={incrementMonth} class="p-3 pr-1">
    <span class="text-3xl text-gray-500">&rsaquo;</span>
  </button>
</div>
