// src/lib/components/creation/CalendarV2/CalendarBodyDay.svelte
<script lang="ts">
  import type { ZotDate } from "$lib/utils/ZotDate";
  import { cn } from "$lib/utils/utils";

  export let isHighlighted: boolean | null;
  export let calendarDay: ZotDate;
  export let isCurrentMonth: boolean;

  $: isSelected = calendarDay.isSelected;
</script>

<p
  class={cn(
    "flex-center relative aspect-square h-8 w-8 rounded-lg text-base font-medium text-gray-dark md:h-12 md:w-12 md:rounded-xl md:text-xl",
    isSelected && "bg-primary text-gray-50",
    isHighlighted && "bg-slate-base text-gray-dark",
    !isCurrentMonth &&
      cn(
        "text-gray-base",
        isHighlighted && "bg-opacity-30",
        isSelected && "bg-opacity-50 text-gray-100",
      ),
  )}
  data-day={calendarDay.getDay()}
  data-month={calendarDay.getMonth()}
  data-year={calendarDay.getYear()}
  data-selected={isSelected}
>
  {calendarDay.getDay()}
</p>

// src/components/creation/calendar/calendar-body-day.tsx
import React from "react";
import { cn } from "@/lib/utils";
import { ZotDate } from "@/lib/zotdate";

interface CalendarBodyDayProps {
    isHighlighted: boolean;
    calendarDay: ZotDate;
    isCurrentMonth: boolean;
}

export function CalendarBodyDay({
    isHighlighted,
    calendarDay,
    isCurrentMonth,
}: CalendarBodyDayProps) {
    const isSelected = calendarDay.isSelected;

    return (
        <p
            className={cn(
                "flex-center text-gray-dark relative aspect-square h-8 w-8 rounded-lg text-base font-medium md:h-12 md:w-12 md:rounded-xl md:text-xl",
                isSelected && "bg-primary text-gray-50",
                isHighlighted && "bg-slate-base text-gray-dark",
                !isCurrentMonth &&
                    cn(
                        "text-gray-base",
                        isHighlighted && "bg-opacity-30",
                        isSelected && "bg-opacity-50 text-gray-100"
                    )
            )}
            data-day={calendarDay.getDay()}
            data-month={calendarDay.getMonth()}
            data-year={calendarDay.getYear()}
            data-selected={isSelected}
        >
            {calendarDay.getDay()}
        </p>
    );
}
