// src/lib/components/meetingSetup/Calendar/CalendarBodyDay.svelte
<script lang="ts">
  import type { ZotDate } from "$lib/utils/ZotDate";

  export let isHighlighted: boolean | null;
  export let calendarDay: ZotDate;
</script>

{#if isHighlighted}
  <div
    class="absolute left-1/2 top-1/2 h-10 w-10 -translate-x-1/2 -translate-y-1/2 rounded-full bg-primary-200"
  ></div>
{:else if calendarDay.isSelected}
  <div
    class="absolute left-1/2 top-1/2 h-10 w-10 -translate-x-1/2 -translate-y-1/2 rounded-full bg-primary-400"
  ></div>
{/if}

<p
  class="relative p-2 text-base font-medium text-gray-500"
  data-day={calendarDay.getDay()}
  data-month={calendarDay.getMonth()}
  data-year={calendarDay.getYear()}
  data-selected={calendarDay.isSelected}
>
  {calendarDay.getDay()}
</p>

// src/components/creation/calendar/calendar-body-day.tsx
import React from "react";
import { cn } from "@/lib/utils";
import { ZotDate } from "@/lib/zotdate";

interface CalendarBodyDayProps {
    isHighlighted: boolean;
    calendarDay: ZotDate;
    isCurrentMonth: boolean;
}

export function CalendarBodyDay({
    isHighlighted,
    calendarDay,
    isCurrentMonth,
}: CalendarBodyDayProps) {
    const isSelected = calendarDay.isSelected;

    return (
        <p
            className={cn(
                "flex-center text-gray-dark relative aspect-square h-8 w-8 rounded-lg text-base font-medium md:h-12 md:w-12 md:rounded-xl md:text-xl",
                isSelected && "bg-primary text-gray-50",
                isHighlighted && "bg-slate-base text-gray-dark",
                !isCurrentMonth &&
                    cn(
                        "text-gray-base",
                        isHighlighted && "bg-opacity-30",
                        isSelected && "bg-opacity-50 text-gray-100"
                    )
            )}
            data-day={calendarDay.getDay()}
            data-month={calendarDay.getMonth()}
            data-year={calendarDay.getYear()}
            data-selected={isSelected}
        >
            {calendarDay.getDay()}
        </p>
    );
}
