// src/components/availability/group-availability.tsx
"use client";

import React, { useEffect, useState } from "react";
import { useAvailabilityContext } from "@/components/availability/context/availability-context";
import { GroupAvailabilityBlock } from "@/components/availability/group-availability-block";
import { GroupResponses } from "@/components/availability/group-responses";
import { AvailabilityNavButton } from "@/components/availability/table/availability-nav-button";
import { AvailabilityTableHeader } from "@/components/availability/table/availability-table-header";
import { AvailabilityTimeTicks } from "@/components/availability/table/availability-time-ticks";
import { MemberMeetingAvailability } from "@/lib/types/availability";
import { cn } from "@/lib/utils";
import { ZotDate } from "@/lib/zotdate";

export const getTimestampFromBlockIndex = (
    blockIndex: number,
    zotDateIndex: number,
    fromTime: number,
    availabilityDates: ZotDate[]
) => {
    const minutesFromMidnight = fromTime * 60 + blockIndex * 15;
    const hours = Math.floor(minutesFromMidnight / 60);
    const minutes = minutesFromMidnight % 60;

    const selectedDate = availabilityDates.at(zotDateIndex);

    if (!selectedDate) {
        return "";
    }

    const date = new Date(selectedDate.day);
    date.setHours(hours);
    date.setMinutes(minutes);
    date.setSeconds(0);
    date.setMilliseconds(0);

    const isoString = date.toISOString();
    // console.log(`Block ${blockIndex} corresponds to time ${isoString}`);
    return isoString;
};

interface GroupAvailabilityProps {
    availabilityTimeBlocks: number[];
    groupAvailabilities: MemberMeetingAvailability[];
    fromTime: number;
    toTime: number;
}
export function GroupAvailability({
    availabilityTimeBlocks,
    groupAvailabilities,
    fromTime,
}: GroupAvailabilityProps) {
    const {
        currentPage,
        setCurrentPage,
        itemsPerPage,
        currentPageAvailability,
        setCurrentPageAvailability,
        availabilityDates,
    } = useAvailabilityContext();

    const lastPage = Math.floor((availabilityDates.length - 1) / itemsPerPage);
    const numPaddingDates =
        availabilityDates.length % itemsPerPage === 0
            ? 0
            : itemsPerPage - (availabilityDates.length % itemsPerPage);

    const [isMobileDrawerOpen, setIsMobileDrawerOpen] = useState(false);
    const [selectedZotDateIndex, setSelectedZotDateIndex] = useState<number>();
    const [selectedBlockIndex, setSelectedBlockIndex] = useState<number>();
    const [availableMembersOfSelection, setAvailableMembersOfSelection] =
        useState<string[]>([]);
    const [notAvailableMembersOfSelection, setNotAvailableMembersOfSelection] =
        useState<string[]>([]);

    const [selectionIsLocked, setSelectionIsLocked] = useState(false);
    const [hoveredMember, setHoveredMember] = useState<string | null>(null);

    const generateDateKey = ({
        selectedDate,
        timeBlock,
        pageDateIndex,
    }: {
        selectedDate: ZotDate;
        timeBlock: number;
        pageDateIndex: number;
    }) => {
        return selectedDate
            ? `date-${selectedDate.valueOf()}-${timeBlock}`
            : `padding-${pageDateIndex}`;
    };

    const updateSelection = ({
        zotDateIndex,
        blockIndex,
    }: {
        zotDateIndex: number;
        blockIndex: number;
    }) => {
        setIsMobileDrawerOpen(true);
        setSelectedZotDateIndex(zotDateIndex);
        setSelectedBlockIndex(blockIndex);
    };

    const resetSelection = () => {
        setIsMobileDrawerOpen(false);
        setSelectedZotDateIndex(undefined);
        setSelectedBlockIndex(undefined);
    };

    const handleCellClick = ({
        isSelected,
        zotDateIndex,
        blockIndex,
    }: {
        isSelected: boolean;
        zotDateIndex: number;
        blockIndex: number;
    }) => {
        if (selectionIsLocked && isSelected) {
            setSelectionIsLocked(false);
        } else {
            setSelectionIsLocked(true);
            updateSelection({ zotDateIndex, blockIndex });
        }
    };

    const handleCellHover = ({
        zotDateIndex,
        blockIndex,
    }: {
        zotDateIndex: number;
        blockIndex: number;
    }) => {
        if (!selectionIsLocked) {
            updateSelection({ zotDateIndex, blockIndex });
        }
    };

    const handlePrevPage = () => {
        if (currentPage > 0) {
            setCurrentPage(currentPage - 1);
        }
    };

    const handleNextPage = () => {
        if (currentPage < lastPage) {
            setCurrentPage(currentPage + 1);
        }
    };

    // Update current page availability on pagination or data change
    useEffect(() => {
        const datesToOffset = currentPage * itemsPerPage;
        let newCurrentPageAvailability = availabilityDates.slice(
            datesToOffset,
            datesToOffset + itemsPerPage
        );

        if (currentPage === lastPage) {
            newCurrentPageAvailability = newCurrentPageAvailability.concat(
                new Array(numPaddingDates).fill(null)
            );
        }

        setCurrentPageAvailability(newCurrentPageAvailability);
    }, [
        currentPage,
        itemsPerPage,
        availabilityDates,
        numPaddingDates,
        lastPage,
    ]);

    // Update selection members when selection changes
    useEffect(() => {
        if (
            selectedZotDateIndex !== undefined &&
            selectedBlockIndex !== undefined
        ) {
            const selectedDate = availabilityDates[selectedZotDateIndex];
            const timestamp = getTimestampFromBlockIndex(
                selectedBlockIndex,
                selectedZotDateIndex,
                fromTime,
                availabilityDates
            );

            const availableMembers =
                selectedDate.groupAvailability[timestamp] || [];
            setAvailableMembersOfSelection(availableMembers);

            const notAvailableMembers = groupAvailabilities.filter(
                (member) => !availableMembers.includes(member.memberId)
            );
            setNotAvailableMembersOfSelection(
                notAvailableMembers.map((member) => member.memberId)
            );
        }
    }, [
        setCurrentPageAvailability,
        selectedZotDateIndex,
        selectedBlockIndex,
        availabilityDates,
        groupAvailabilities,
    ]);

    useEffect(() => {
        const handleClickOutside = (event: MouseEvent) => {
            const target = event.target as Element;
            const isOnAvailabilityBlock = !!target.closest('.group-availability-block');
            
            if (!isOnAvailabilityBlock) {
                resetSelection();
                setSelectionIsLocked(false);
            }
        };

        document.addEventListener("mousedown", handleClickOutside);
        return () => {
            document.removeEventListener("mousedown", handleClickOutside);
        };
    }, []);

    useEffect(() => {
        const handleEscKey = (event: KeyboardEvent) => {
            if (event.key === 'Escape') {
                resetSelection();
                setSelectionIsLocked(false);
                // removes weird outline
                if (document.activeElement instanceof HTMLElement) {
                    document.activeElement.blur();
                }
            }
        };
        
        document.addEventListener('keydown', handleEscKey);
        return () => {
            document.removeEventListener('keydown', handleEscKey);
        };
    }, []);

    const handleMemberHover = (memberId: string | null) => {
        setHoveredMember(memberId);
    };

    console.log(fromTime, availabilityDates);

    return (
        <div className="flex flex-row items-start justify-start align-top">
            <div 
                className="flex items-center justify-between overflow-x-auto h-fit font-dm-sans lg:w-full lg:pr-10"
            >
                <AvailabilityNavButton
                    direction="left"
                    handleClick={handlePrevPage}
                    disabled={currentPage === 0}
                />

                <table className="w-full table-fixed">
                    <AvailabilityTableHeader />

                    <tbody>
                        {availabilityTimeBlocks.map((timeBlock, blockIndex) => {
                            const isTopOfHour = timeBlock % 60 === 0;
                            const isHalfHour = timeBlock % 60 === 30;
                            const isLastRow =
                                blockIndex ===
                                availabilityTimeBlocks.length - 1;

                            return (
                                <tr key={`block-${timeBlock}`}>
                                    <AvailabilityTimeTicks
                                        timeBlock={timeBlock}
                                    />
                                    {/* DOES THIS BREAK ANYTHING??? */}
                                    {currentPageAvailability?.filter(date => date !== null).map(
                                        (selectedDate, pageDateIndex) => {
                                            const key = generateDateKey({
                                                selectedDate,
                                                timeBlock,
                                                pageDateIndex,
                                            });

                                            if (selectedDate) {
                                                const zotDateIndex =
                                                    pageDateIndex +
                                                    currentPage * itemsPerPage;

                                                const isSelected =
                                                    selectedZotDateIndex ===
                                                        zotDateIndex &&
                                                    selectedBlockIndex ===
                                                        blockIndex;
                                                        
                                                const timestamp =
                                                    getTimestampFromBlockIndex(
                                                        blockIndex,
                                                        zotDateIndex,
                                                        fromTime,
                                                        availabilityDates
                                                    );
                                                
                                                const isMemberAvailableAtTimestamp = hoveredMember && 
                                                    selectedDate.groupAvailability[timestamp] && 
                                                    selectedDate.groupAvailability[timestamp].includes(hoveredMember);
                                                
                                                const tableCellStyles = cn(
                                                    isTopOfHour &&
                                                        "border-t-[1px] border-t-gray-medium",
                                                    isHalfHour &&
                                                        "border-t-[1px] border-t-gray-base",
                                                    isLastRow &&
                                                        "border-b-[1px]",
                                                    isSelected &&
                                                        "outline-dashed outline-2 outline-slate-500"
                                                );

                                                return (
                                                    <td
                                                        key={key}
                                                        className="px-0 py-0"
                                                    >
                                                        <GroupAvailabilityBlock
                                                            className="hidden lg:block group-availability-block"
                                                            timestamp={
                                                                timestamp
                                                            }
                                                            onClick={() =>
                                                                handleCellClick(
                                                                    {
                                                                        isSelected,
                                                                        zotDateIndex,
                                                                        blockIndex,
                                                                    }
                                                                )
                                                            }
                                                            onHover={() =>
                                                                handleCellHover(
                                                                    {
                                                                        zotDateIndex,
                                                                        blockIndex,
                                                                    }
                                                                )
                                                            }
                                                            groupAvailabilities={
                                                                availabilityDates
                                                            }
                                                            tableCellStyles={
                                                                tableCellStyles
                                                            }
                                                            hoveredMember={hoveredMember}
                                                        />
                                                        <GroupAvailabilityBlock
                                                            timestamp={
                                                                timestamp
                                                            }
                                                            className="block lg:hidden group-availability-block"
                                                            onClick={() =>
                                                                handleCellClick(
                                                                    {
                                                                        isSelected,
                                                                        zotDateIndex,
                                                                        blockIndex,
                                                                    }
                                                                )
                                                            }
                                                            groupAvailabilities={
                                                                availabilityDates
                                                            }
                                                            tableCellStyles={
                                                                tableCellStyles
                                                            }
                                                            hoveredMember={hoveredMember}
                                                        />
                                                    </td>
                                                );
                                            } else {
                                                return <td key={key}></td>;
                                            }
                                        }
                                    )}
                                </tr>
                            );
                        })}
                    </tbody>
                </table>

                <AvailabilityNavButton
                    direction="right"
                    handleClick={handleNextPage}
                    disabled={currentPage === lastPage}
                />
            </div>

            <GroupResponses
                availabilityDates={availabilityDates}
                isMobileDrawerOpen={isMobileDrawerOpen}
                selectedZotDateIndex={selectedZotDateIndex}
                selectedBlockIndex={selectedBlockIndex}
                availableMembersOfSelection={availableMembersOfSelection}
                notAvailableMembersOfSelection={notAvailableMembersOfSelection}
                closeMobileDrawer={resetSelection}
                onMemberHover={handleMemberHover}
            />

            <div className={`lg:hidden ${isMobileDrawerOpen ? "h-96" : ""}`} />
        </div>
    );
}

// src/lib/components/availability/GroupAvailability.svelte
<script lang="ts">
  import { onMount } from "svelte";

  import GroupAvailabilityBlock from "$lib/components/availability/GroupAvailabilityBlock.svelte";
  import GroupResponses from "$lib/components/availability/GroupResponses.svelte";
  import {
    availabilityDates,
    availabilityTimeBlocks,
    groupAvailabilities,
  } from "$lib/stores/availabilityStores";
  import { ZotDate } from "$lib/utils/ZotDate";
  import { cn } from "$lib/utils/utils";

  export let columns: number;

  const itemsPerPage: number = columns;
  const lastPage: number = Math.floor(($availabilityDates.length - 1) / itemsPerPage);
  const numPaddingDates: number =
    $availabilityDates.length % itemsPerPage === 0
      ? 0
      : itemsPerPage - ($availabilityDates.length % itemsPerPage);

  let currentPage = 0;
  let currentPageAvailability: (ZotDate | null)[];
  let isMobileDrawerOpen: boolean = false;
  let selectedZotDateIndex: number | null = null;
  let selectedBlockIndex: number | null = null;
  let availableMembersOfSelection: string[] = [];
  let notAvailableMembersOfSelection: string[] = [];
  let selectionIsLocked: boolean = false;

  // TODO: Delete when done debugging
  onMount(() => console.log("groupAvailabilties", $groupAvailabilities));

  // Triggers on every pagination change and selection confirmation
  $: {
    const datesToOffset = currentPage * itemsPerPage;
    currentPageAvailability = $availabilityDates.slice(datesToOffset, datesToOffset + itemsPerPage);

    if (currentPage === lastPage) {
      currentPageAvailability = currentPageAvailability.concat(
        new Array(numPaddingDates).fill(null),
      );
    }
  }

  // Triggers on every selection change
  $: {
    if (selectedZotDateIndex !== null && selectedBlockIndex !== null) {
      const availableMemberIndices: number[] =
        $availabilityDates[selectedZotDateIndex].getGroupAvailabilityBlock(selectedBlockIndex) ??
        [];

      availableMembersOfSelection = availableMemberIndices.map(
        (availableMemberIndex) => $groupAvailabilities[availableMemberIndex].name,
      );

      notAvailableMembersOfSelection = $groupAvailabilities
        .filter((_, index) => !availableMemberIndices.includes(index))
        .map((notAvailableMember) => notAvailableMember.name);
    }
  }

  const generateDateKey = (
    selectedDate: ZotDate | null,
    timeBlock: number,
    pageDateIndex: number,
  ): string => {
    return selectedDate
      ? `date-${selectedDate.valueOf()}-${timeBlock}`
      : `padding-${pageDateIndex}`;
  };

  const updateSelection = (zotDateIndex: number, blockIndex: number): void => {
    isMobileDrawerOpen = true;
    selectedZotDateIndex = zotDateIndex;
    selectedBlockIndex = blockIndex;
  };

  const resetSelection = () => {
    isMobileDrawerOpen = false;
    selectedZotDateIndex = null;
    selectedBlockIndex = null;
  };

  const handleCellClick = (isSelected: boolean, zotDateIndex: number, blockIndex: number) => {
    if (selectionIsLocked && isSelected) {
      selectionIsLocked = false;
    } else {
      selectionIsLocked = true;
      updateSelection(zotDateIndex, blockIndex);
    }
  };

  const handleCellHover = (zotDateIndex: number, blockIndex: number) => {
    if (!selectionIsLocked) {
      updateSelection(zotDateIndex, blockIndex);
    }
  };
</script>

<div class="flex items-center justify-between overflow-x-auto font-dm-sans lg:w-full lg:pr-10">
  <button
    on:click={() => {
      if (currentPage > 0) {
        currentPage = currentPage - 1;
      }
    }}
    class="p-3 disabled:opacity-0 md:pl-1"
    disabled={currentPage === 0}
  >
    <span class="text-3xl text-gray-500">&lsaquo;</span>
  </button>

  <table class="w-full table-fixed">
    <thead>
      <tr>
        <th class="w-10 md:w-16"><span class="sr-only">Time</span></th>
        {#each currentPageAvailability as dateHeader}
          <th class="pb-2 text-sm font-normal">
            {#if dateHeader}
              <div class="flex flex-col">
                <span class="text-[10px] font-bold uppercase text-gray-500 md:text-xs">
                  {dateHeader.day.toLocaleDateString("en-US", {
                    weekday: "short",
                  })}
                </span>

                <span class="text-center text-[12px] uppercase text-gray-medium md:text-base">
                  {dateHeader.day.toLocaleDateString("en-US", {
                    month: "numeric",
                    day: "numeric",
                  })}
                </span>
              </div>
            {/if}
          </th>
        {/each}
      </tr>
    </thead>

    <tbody>
      {#each $availabilityTimeBlocks as timeBlock, blockIndex (`block-${timeBlock}`)}
        {@const isTopOfHour = timeBlock % 60 === 0}
        {@const isHalfHour = timeBlock % 60 === 30}
        {@const isLastRow = blockIndex === $availabilityTimeBlocks.length - 1}
        <tr>
          <td class="w-2 border-r-[1px] border-r-gray-medium py-0 pr-3 align-top">
            {#if isTopOfHour}
              <span
                class="float-right hidden whitespace-nowrap text-[10px] font-bold text-gray-medium md:flex md:text-xs"
              >
                {ZotDate.toTimeBlockString(timeBlock, false)}
              </span>
              <span
                class="float-right flex whitespace-nowrap text-[10px] font-bold text-gray-medium md:hidden md:text-xs"
              >
                {ZotDate.toTimeBlockString(timeBlock, true)}
              </span>
            {/if}
          </td>

          {#each currentPageAvailability as selectedDate, pageDateIndex (generateDateKey(selectedDate, timeBlock, pageDateIndex))}
            {#if selectedDate}
              {@const zotDateIndex = pageDateIndex + currentPage * itemsPerPage}
              {@const availableMemberIndices = selectedDate.getGroupAvailabilityBlock(blockIndex)}
              {@const isSelected =
                selectedZotDateIndex === zotDateIndex && selectedBlockIndex === blockIndex}
              {@const tableCellStyles = cn(
                isTopOfHour && "border-t-[1px] border-t-gray-medium",
                isHalfHour && "border-t-[1px] border-t-gray-base",
                isLastRow && "border-b-[1px]",
                isSelected && "outline-dashed outline-2 outline-slate-500",
              )}

              <td class="px-0 py-0">
                <GroupAvailabilityBlock
                  class="hidden lg:block"
                  onClick={() => {
                    handleCellClick(isSelected, zotDateIndex, blockIndex);
                  }}
                  onHover={() => {
                    // Enable cell hover behavior on large screens to prevent drawer triggers
                    handleCellHover(zotDateIndex, blockIndex);
                  }}
                  {availableMemberIndices}
                  {tableCellStyles}
                />
                <GroupAvailabilityBlock
                  class="block lg:hidden"
                  onClick={() => {
                    handleCellClick(isSelected, zotDateIndex, blockIndex);
                  }}
                  {availableMemberIndices}
                  {tableCellStyles}
                />
              </td>
            {:else}
              <td></td>
            {/if}
          {/each}
        </tr>
      {/each}
    </tbody>
  </table>

  <button
    on:click={() => {
      if (currentPage < lastPage) {
        currentPage = currentPage + 1;
      }
    }}
    class="p-3 disabled:opacity-0 md:pr-1"
    disabled={currentPage === lastPage}
  >
    <span class="text-3xl text-gray-500">&rsaquo;</span>
  </button>
</div>

<GroupResponses
  {isMobileDrawerOpen}
  {selectedZotDateIndex}
  {selectedBlockIndex}
  {availableMembersOfSelection}
  {notAvailableMembersOfSelection}
  closeMobileDrawer={resetSelection}
/>
<div class:h-96={isMobileDrawerOpen} class="lg:hidden" />
