// src/app/components/availability/personal-availability.tsx
"use client";

import { useEffect, useMemo, useState } from "react";
import { AvailabilityBlock } from "@/app/components/availability/availability-block";
import {
    AvailabilityMeetingDateJoinSchema,
    MeetingDateSelectSchema,
    MeetingSelectSchema,
} from "@/db/schema";
import {
    AvailabilityBlockType,
    SelectionStateType,
} from "@/lib/types/availability";
import { cn } from "@/lib/utils";
import { ZotDate } from "@/lib/zotdate";

// import LoginFlow from "./LoginModal";

interface PersonalAvailabilityProps {
    columns: number;
    meetingData: MeetingSelectSchema;
    defaultDates: MeetingDateSelectSchema[];
    availability: AvailabilityMeetingDateJoinSchema[] | null;
}

export function PersonalAvailability({
    columns,
    meetingData,
    defaultDates,
    availability,
}: PersonalAvailabilityProps) {
    const [itemsPerPage, setItemsPerPage] = useState(columns);
    const [availabilityDates, setAvailabilityDates] = useState<ZotDate[]>([]);
    const [availabilityTimeBlocks, setAvailabilityTimeBlocks] = useState<
        number[]
    >([]);
    const [guestSession, setGuestSession] = useState({
        meetingId: meetingData.id || "",
    });
    const [isEditingAvailability, setIsEditingAvailability] = useState(false);
    const [isStateUnsaved, setIsStateUnsaved] = useState(false);

    const [startBlockSelection, setStartBlockSelection] =
        useState<AvailabilityBlockType>();
    const [endBlockSelection, setEndBlockSelection] =
        useState<AvailabilityBlockType>();
    const [selectionState, setSelectionState] = useState<SelectionStateType>();

    const [currentPage, setCurrentPage] = useState(0);
    const [currentPageAvailability, setCurrentPageAvailability] =
        useState<ZotDate[]>();

    useEffect(() => {
        setItemsPerPage(columns);
    }, [columns]);

    const numPaddingDates = useMemo(() => {
        return availabilityDates.length % itemsPerPage === 0
            ? 0
            : itemsPerPage - (availabilityDates.length % itemsPerPage);
    }, [availabilityDates.length, itemsPerPage]);

    const lastPage = useMemo(() => {
        return Math.floor((availabilityDates.length - 1) / itemsPerPage);
    }, [availabilityDates.length, itemsPerPage]);

    useEffect(() => {
        const datesToOffset = currentPage * itemsPerPage;
        let pageAvailability = availabilityDates.slice(
            datesToOffset,
            datesToOffset + itemsPerPage
        );

        if (currentPage === lastPage) {
            pageAvailability = pageAvailability.concat(
                new Array(numPaddingDates).fill(null)
            );
        }
        setCurrentPageAvailability(pageAvailability);
    }, [
        currentPage,
        itemsPerPage,
        availabilityDates,
        lastPage,
        numPaddingDates,
    ]);

    useEffect(() => {
        if (startBlockSelection && endBlockSelection) {
            setSelectionState({
                earlierDateIndex: Math.min(
                    startBlockSelection.zotDateIndex,
                    endBlockSelection.zotDateIndex
                ),
                laterDateIndex: Math.max(
                    startBlockSelection.zotDateIndex,
                    endBlockSelection.zotDateIndex
                ),
                earlierBlockIndex: Math.min(
                    startBlockSelection.blockIndex,
                    endBlockSelection.blockIndex
                ),
                laterBlockIndex: Math.max(
                    startBlockSelection.blockIndex,
                    endBlockSelection.blockIndex
                ),
            });
        }
    }, [startBlockSelection, endBlockSelection]);

    const generateDateKey = (
        selectedDate: ZotDate,
        timeBlock: number,
        pageDateIndex: number
    ) => {
        return selectedDate
            ? `date-${selectedDate.valueOf()}-${timeBlock}`
            : `padding-${pageDateIndex}`;
    };

    const handleTouchMove = (e: React.TouchEvent) => {
        const touchingElement = document.elementFromPoint(
            e.touches[0].clientX,
            e.touches[0].clientY
        );

        if (!touchingElement) return;

        const touchingDateIndex = parseInt(
            touchingElement.getAttribute("data-date-index") || "",
            10
        );
        const touchingBlockIndex = parseInt(
            touchingElement.getAttribute("data-block-index") || "",
            10
        );

        if (
            !isNaN(touchingDateIndex) &&
            !isNaN(touchingBlockIndex) &&
            startBlockSelection
        ) {
            setEndBlockSelection({
                zotDateIndex: touchingDateIndex,
                blockIndex: touchingBlockIndex,
            });
        }
    };

    const setAvailabilities = (startBlock: AvailabilityBlockType) => {
        if (!isEditingAvailability) {
            setIsEditingAvailability(true);
        }

        if (selectionState) {
            const {
                earlierDateIndex,
                laterDateIndex,
                earlierBlockIndex,
                laterBlockIndex,
            } = selectionState;
            const {
                zotDateIndex: selectionStartDateIndex,
                blockIndex: selectionStartBlockIndex,
            } = startBlock;

            const startSelectionZotDate =
                availabilityDates[selectionStartDateIndex];
            const selectionValue = !startSelectionZotDate.getBlockAvailability(
                selectionStartBlockIndex
            );

            setAvailabilityDates((currentAvailabilityDates) => {
                const updatedDates = [...currentAvailabilityDates];
                for (
                    let dateIndex = earlierDateIndex;
                    dateIndex <= laterDateIndex;
                    dateIndex++
                ) {
                    const currentDate = updatedDates[dateIndex];
                    currentDate.setBlockAvailabilities(
                        earlierBlockIndex,
                        laterBlockIndex,
                        selectionValue
                    );
                }
                return updatedDates;
            });

            setStartBlockSelection(null);
            setEndBlockSelection(null);
            setSelectionState(null);
            setIsStateUnsaved(true);
        }
    };

    useEffect(() => {
        const handleBeforeUnload = (event: BeforeUnloadEvent) => {
            if (isStateUnsaved) {
                event.preventDefault();
                event.returnValue =
                    "Are you sure you want to leave? You have unsaved changes!";
            }
        };

        window.addEventListener("beforeunload", handleBeforeUnload);

        return () => {
            window.removeEventListener("beforeunload", handleBeforeUnload);
        };
    }, [isStateUnsaved]);

    // useEffect(() => {
    //     const init = async () => {
    //         setGuestSession((prev) => ({
    //             ...prev,
    //             meetingId: meetingData.id || "",
    //         }));

    //         // const generalAvailability = await getGeneralAvailability(
    //         //     meetingData,
    //         //     guestSession
    //         // );

    //         const generalAvailability: Array<unknown> | null = null;

    //         const defaultMeetingDates = defaultDates.map(
    //             (item) => new ZotDate(item.date, false, [])
    //         );

    //         ZotDate.initializeAvailabilities(defaultMeetingDates);

    //         setAvailabilityDates(
    //             generalAvailability && generalAvailability.length > 0
    //                 ? generalAvailability
    //                 : defaultMeetingDates
    //         );
    //     };

    //     init();
    // }, [defaultDates, guestSession, meetingData]);

    // Sample availabilityTimeBlocks; replace with your actual data
    useEffect(() => {
        // Replace with your actual logic to set availabilityTimeBlocks
        setAvailabilityTimeBlocks([0, 30, 60, 90, 120, 150, 180]);
    }, []);

    const handlePrevPage = () => {
        if (currentPage > 0) {
            setCurrentPage(currentPage - 1);
        }
    };

    const handleNextPage = () => {
        if (currentPage < lastPage) {
            setCurrentPage(currentPage + 1);
        }
    };

    return (
        <div>
            <div className="font-dm-sans flex items-center justify-between overflow-x-auto">
                <button
                    onClick={handlePrevPage}
                    className="p-3 pl-0 disabled:opacity-0 md:pl-1"
                    disabled={currentPage === 0}
                >
                    <span className="text-3xl text-gray-500">&lsaquo;</span>
                </button>

                <table className="w-full table-fixed">
                    <thead>
                        <tr>
                            <th className="w-10 md:w-16">
                                <span className="sr-only">Time</span>
                            </th>
                            {currentPageAvailability?.map(
                                (dateHeader, index) => (
                                    <th
                                        key={index}
                                        className="text-sm font-normal"
                                    >
                                        {dateHeader && (
                                            <div className="flex flex-col">
                                                <span className="text-[10px] font-bold uppercase text-gray-500 md:text-xs">
                                                    {dateHeader.day.toLocaleDateString(
                                                        "en-US",
                                                        { weekday: "short" }
                                                    )}
                                                </span>
                                                <span className="text-gray-medium text-center text-[12px] uppercase md:text-base">
                                                    {dateHeader.day.toLocaleDateString(
                                                        "en-US",
                                                        {
                                                            month: "numeric",
                                                            day: "numeric",
                                                        }
                                                    )}
                                                </span>
                                            </div>
                                        )}
                                    </th>
                                )
                            )}
                        </tr>
                    </thead>

                    <tbody>
                        {availabilityTimeBlocks.map((timeBlock, blockIndex) => {
                            const isTopOfHour = timeBlock % 60 === 0;
                            const isHalfHour = timeBlock % 60 === 30;
                            const isLastRow =
                                blockIndex ===
                                availabilityTimeBlocks.length - 1;

                            return (
                                <tr key={`block-${timeBlock}`}>
                                    <td className="border-r-gray-medium w-2 border-r-[1px] py-0 pr-3 align-top">
                                        {isTopOfHour && (
                                            <>
                                                <span className="text-gray-medium float-right hidden whitespace-nowrap text-[10px] font-bold md:flex md:text-xs">
                                                    {ZotDate.toTimeBlockString(
                                                        timeBlock,
                                                        false
                                                    )}
                                                </span>
                                                <span className="text-gray-medium float-right flex whitespace-nowrap text-[10px] font-bold md:hidden md:text-xs">
                                                    {ZotDate.toTimeBlockString(
                                                        timeBlock,
                                                        true
                                                    )}
                                                </span>
                                            </>
                                        )}
                                    </td>

                                    {currentPageAvailability?.map(
                                        (selectedDate, pageDateIndex) => {
                                            const key = generateDateKey(
                                                selectedDate,
                                                timeBlock,
                                                pageDateIndex
                                            );

                                            if (selectedDate) {
                                                const zotDateIndex =
                                                    pageDateIndex +
                                                    currentPage * itemsPerPage;
                                                const availabilitySelection = {
                                                    zotDateIndex: zotDateIndex,
                                                    blockIndex: blockIndex,
                                                };
                                                const isAvailable =
                                                    selectedDate.getBlockAvailability(
                                                        blockIndex
                                                    );

                                                return (
                                                    <td
                                                        key={key}
                                                        onMouseUp={() => {
                                                            if (
                                                                startBlockSelection
                                                            ) {
                                                                setEndBlockSelection(
                                                                    availabilitySelection
                                                                );
                                                                setAvailabilities(
                                                                    startBlockSelection
                                                                );
                                                            }
                                                        }}
                                                        className="px-0 py-0"
                                                    >
                                                        <button
                                                            onTouchStart={(
                                                                e
                                                            ) => {
                                                                if (
                                                                    e.cancelable
                                                                ) {
                                                                    e.preventDefault();
                                                                }
                                                                setStartBlockSelection(
                                                                    availabilitySelection
                                                                );
                                                                setEndBlockSelection(
                                                                    availabilitySelection
                                                                );
                                                            }}
                                                            onMouseDown={() => {
                                                                setStartBlockSelection(
                                                                    availabilitySelection
                                                                );
                                                                setEndBlockSelection(
                                                                    availabilitySelection
                                                                );
                                                            }}
                                                            onTouchMove={
                                                                handleTouchMove
                                                            }
                                                            onMouseMove={() => {
                                                                if (
                                                                    startBlockSelection
                                                                ) {
                                                                    setEndBlockSelection(
                                                                        availabilitySelection
                                                                    );
                                                                }
                                                            }}
                                                            onTouchEnd={(e) => {
                                                                if (
                                                                    e.cancelable
                                                                ) {
                                                                    e.preventDefault();
                                                                }
                                                                if (
                                                                    startBlockSelection
                                                                ) {
                                                                    setEndBlockSelection(
                                                                        availabilitySelection
                                                                    );
                                                                    setAvailabilities(
                                                                        startBlockSelection
                                                                    );
                                                                }
                                                            }}
                                                            // TODO: Fix
                                                            // tabIndex="0"
                                                            data-date-index={
                                                                zotDateIndex
                                                            }
                                                            data-block-index={
                                                                blockIndex
                                                            }
                                                            className={cn(
                                                                "border-gray-medium block h-full w-full cursor-row-resize border-r-[1px]",
                                                                isTopOfHour &&
                                                                    "border-t-gray-medium border-t-[1px]",
                                                                isHalfHour &&
                                                                    "border-t-gray-base border-t-[1px]",
                                                                isLastRow &&
                                                                    "border-b-[1px]"
                                                            )}
                                                        >
                                                            <AvailabilityBlock
                                                                isAvailable={
                                                                    isAvailable
                                                                }
                                                                zotDateIndex={
                                                                    zotDateIndex
                                                                }
                                                                blockIndex={
                                                                    blockIndex
                                                                }
                                                                selectionState={
                                                                    selectionState
                                                                }
                                                            />
                                                        </button>
                                                    </td>
                                                );
                                            } else {
                                                return <td key={key}></td>;
                                            }
                                        }
                                    )}
                                </tr>
                            );
                        })}
                    </tbody>
                </table>

                <button
                    onClick={handleNextPage}
                    className="p-3 pr-0 disabled:opacity-0 md:pr-1"
                    disabled={currentPage === lastPage}
                >
                    <span className="text-3xl text-gray-500">&rsaquo;</span>
                </button>
            </div>

            {/* <LoginFlow data={data} /> */}
        </div>
    );
}

export default PersonalAvailability;

// src/lib/components/availability/PersonalAvailability.svelte
<script lang="ts">
  import { onMount } from "svelte";

  import type { PageData } from "../../../routes/availability/$types";

  import LoginFlow from "./LoginModal.svelte";

  import AvailabilityBlock from "$lib/components/availability/AvailabilityBlock.svelte";
  import {
    availabilityDates,
    availabilityTimeBlocks,
    guestSession,
    isEditingAvailability,
    isStateUnsaved,
  } from "$lib/stores/availabilityStores";
  import type { AvailabilityBlockType, SelectionStateType } from "$lib/types/availability";
  import { ZotDate } from "$lib/utils/ZotDate";
  import { getGeneralAvailability } from "$lib/utils/availability";
  import { cn } from "$lib/utils/utils";

  export let columns: number;
  export let data: PageData;

  let itemsPerPage: number = columns;
  $: {
    itemsPerPage = columns;
  }

  const lastPage: number = Math.floor(($availabilityDates.length - 1) / itemsPerPage);
  const numPaddingDates: number =
    $availabilityDates.length % itemsPerPage === 0
      ? 0
      : itemsPerPage - ($availabilityDates.length % itemsPerPage);

  let startBlockSelection: AvailabilityBlockType | null = null;
  let endBlockSelection: AvailabilityBlockType | null = null;

  let currentPage = 0;

  let currentPageAvailability: (ZotDate | null)[];

  let selectionState: SelectionStateType | null = null;

  // Triggers on every pagination change and selection confirmation
  $: {
    const datesToOffset = currentPage * itemsPerPage;

    currentPageAvailability = $availabilityDates.slice(datesToOffset, datesToOffset + itemsPerPage);

    if (currentPage === lastPage) {
      currentPageAvailability = currentPageAvailability.concat(
        new Array(numPaddingDates).fill(null),
      );
    }
  }

  // Because a user can select in two dimensions, need separate state to keep track of the
  // "correct orientation" of the min and max selection indices
  $: {
    if (startBlockSelection && endBlockSelection) {
      selectionState = {
        earlierDateIndex: Math.min(
          startBlockSelection.zotDateIndex,
          endBlockSelection.zotDateIndex,
        ),
        laterDateIndex: Math.max(startBlockSelection.zotDateIndex, endBlockSelection.zotDateIndex),
        earlierBlockIndex: Math.min(startBlockSelection.blockIndex, endBlockSelection.blockIndex),
        laterBlockIndex: Math.max(startBlockSelection.blockIndex, endBlockSelection.blockIndex),
      };
    }
  }

  const generateDateKey = (
    selectedDate: ZotDate | null,
    timeBlock: number,
    pageDateIndex: number,
  ): string => {
    return selectedDate
      ? `date-${selectedDate.valueOf()}-${timeBlock}`
      : `padding-${pageDateIndex}`;
  };

  /**
   * Updates the current selection whenever a mobile user drags over a block
   * @param e a TouchEvent object from a mobile user
   */
  const handleTouchMove = (e: TouchEvent): void => {
    const touchingElement: Element | null = document.elementFromPoint(
      e.touches[0].clientX,
      e.touches[0].clientY,
    );

    if (!touchingElement) return;

    const touchingDateIndex = parseInt(touchingElement.getAttribute("data-date-index") ?? "");
    const touchingBlockIndex = parseInt(touchingElement.getAttribute("data-block-index") ?? "");

    if (
      !Number.isNaN(touchingDateIndex) &&
      !Number.isNaN(touchingBlockIndex) &&
      startBlockSelection
    ) {
      endBlockSelection = {
        zotDateIndex: touchingDateIndex,
        blockIndex: touchingBlockIndex,
      };
    }
  };

  /**
   * Modifies the selected meeting date availabilities according to the current selection
   * @param startBlock the time block that the user originated the selection
   */
  const setAvailabilities = (startBlock: AvailabilityBlockType): void => {
    if (!$isEditingAvailability) {
      $isEditingAvailability = true;
    }

    if (selectionState) {
      // Destructure user's selection state
      const { earlierDateIndex, laterDateIndex, earlierBlockIndex, laterBlockIndex } =
        selectionState;
      const { zotDateIndex: selectionStartDateIndex, blockIndex: selectionStartBlockIndex } =
        startBlock;

      // Determine behavior of the selection
      const startSelectionZotDate = $availabilityDates[selectionStartDateIndex];
      const selectionValue: boolean =
        !startSelectionZotDate.getBlockAvailability(selectionStartBlockIndex);

      availabilityDates.update((currentAvailabilityDates: ZotDate[]) => {
        for (let dateIndex = earlierDateIndex; dateIndex <= laterDateIndex; dateIndex++) {
          const currentDate = currentAvailabilityDates[dateIndex];
          currentDate.setBlockAvailabilities(earlierBlockIndex, laterBlockIndex, selectionValue);
        }

        return currentAvailabilityDates;
      });

      startBlockSelection = null;
      endBlockSelection = null;
      selectionState = null;

      $isStateUnsaved = true;
    }
  };

  if (typeof window !== "undefined") {
    window.addEventListener("beforeunload", (event) => {
      if ($isStateUnsaved) {
        event.returnValue = `Are you sure you want to leave? You have unsaved changes!`;
      }
    });
  }

  onMount(async () => {
    $guestSession.meetingId = data.meetingId;

    const generalAvailability = await getGeneralAvailability(data, $guestSession);
    const defaultMeetingDates = data.defaultDates.map((item) => new ZotDate(item.date, false, []));
    ZotDate.initializeAvailabilities(defaultMeetingDates);

    $availabilityDates =
      generalAvailability && generalAvailability.length > 0
        ? generalAvailability
        : defaultMeetingDates;
  });
</script>

<div class="flex items-center justify-between overflow-x-auto font-dm-sans">
  <button
    on:click={() => {
      if (currentPage > 0) {
        currentPage = currentPage - 1;
      }
    }}
    class="p-3 pl-0 disabled:opacity-0 md:pl-1"
    disabled={currentPage === 0}
  >
    <span class="text-3xl text-gray-500">&lsaquo;</span>
  </button>

  <table class="w-full table-fixed">
    <thead>
      <tr>
        <th class="w-10 md:w-16"><span class="sr-only">Time</span></th>
        {#each currentPageAvailability as dateHeader}
          <th class="text-sm font-normal">
            {#if dateHeader}
              <div class="flex flex-col">
                <span class="text-[10px] font-bold uppercase text-gray-500 md:text-xs">
                  {dateHeader.day.toLocaleDateString("en-US", {
                    weekday: "short",
                  })}
                </span>

                <span class="text-center text-[12px] uppercase text-gray-medium md:text-base">
                  {dateHeader.day.toLocaleDateString("en-US", {
                    month: "numeric",
                    day: "numeric",
                  })}
                </span>
              </div>
            {/if}
          </th>
        {/each}
      </tr>
    </thead>

    <tr class="h-2" />

    <tbody>
      {#each $availabilityTimeBlocks as timeBlock, blockIndex (`block-${timeBlock}`)}
        {@const isTopOfHour = timeBlock % 60 === 0}
        {@const isHalfHour = timeBlock % 60 === 30}
        {@const isLastRow = blockIndex === $availabilityTimeBlocks.length - 1}
        <tr>
          <td class="w-2 border-r-[1px] border-r-gray-medium py-0 pr-3 align-top">
            {#if isTopOfHour}
              <span
                class="float-right hidden whitespace-nowrap text-[10px] font-bold text-gray-medium md:flex md:text-xs"
              >
                {ZotDate.toTimeBlockString(timeBlock, false)}
              </span>
              <span
                class="float-right flex whitespace-nowrap text-[10px] font-bold text-gray-medium md:hidden md:text-xs"
              >
                {ZotDate.toTimeBlockString(timeBlock, true)}
              </span>
            {/if}
          </td>

          {#each currentPageAvailability as selectedDate, pageDateIndex (generateDateKey(selectedDate, timeBlock, pageDateIndex))}
            {#if selectedDate}
              {@const zotDateIndex = pageDateIndex + currentPage * itemsPerPage}
              {@const availabilitySelection = {
                zotDateIndex: zotDateIndex,
                blockIndex: blockIndex,
              }}
              {@const isAvailable = selectedDate.getBlockAvailability(blockIndex)}

              <td
                on:mouseup={() => {
                  if (startBlockSelection) {
                    endBlockSelection = availabilitySelection;
                    setAvailabilities(startBlockSelection);
                  }
                }}
                class="px-0 py-0"
              >
                <button
                  on:touchstart={(e) => {
                    if (e.cancelable) {
                      e.preventDefault();
                    }

                    startBlockSelection = availabilitySelection;
                    endBlockSelection = availabilitySelection;
                  }}
                  on:mousedown={() => {
                    startBlockSelection = availabilitySelection;
                    endBlockSelection = availabilitySelection;
                  }}
                  on:touchmove={handleTouchMove}
                  on:mousemove={() => {
                    if (startBlockSelection) {
                      endBlockSelection = availabilitySelection;
                    }
                  }}
                  on:touchend={(e) => {
                    if (e.cancelable) {
                      e.preventDefault();
                    }
                    if (startBlockSelection) {
                      endBlockSelection = availabilitySelection;
                      setAvailabilities(startBlockSelection);
                    }
                  }}
                  tabindex="0"
                  class={cn(
                    "block h-full w-full cursor-row-resize border-r-[1px] border-gray-medium",
                    isTopOfHour && "border-t-[1px] border-t-gray-medium",
                    isHalfHour && "border-t-[1px] border-t-gray-base",
                    isLastRow && "border-b-[1px]",
                  )}
                >
                  <AvailabilityBlock {isAvailable} {zotDateIndex} {blockIndex} {selectionState} />
                </button>
              </td>
            {:else}
              <td></td>
            {/if}
          {/each}
        </tr>
      {/each}
    </tbody>
  </table>

  <button
    on:click={() => {
      if (currentPage < lastPage) {
        currentPage = currentPage + 1;
      }
    }}
    class="p-3 pr-0 disabled:opacity-0 md:pr-1"
    disabled={currentPage === lastPage}
  >
    <span class="text-3xl text-gray-500">&rsaquo;</span>
  </button>
</div>

<LoginFlow {data} />
