// src/components/creation/fields/meeting-time-field.tsx
import React, { Dispatch, SetStateAction, useState } from "react";
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from "@/components/ui/select";
import { HourMinuteString } from "@/lib/types/chrono";
import { ClockIcon } from "lucide-react";

const convertTo24Hour = (hour: number, period: string) => {
	if (period === "PM" && hour !== 12) {
		hour += 12;
	} else if (period === "AM" && hour === 12) {
		hour = 0;
	}
	return hour.toString().padStart(2, "0");
};

const parseHourMinuteString = (
	time: HourMinuteString,
): {
	hour: number;
	period: "AM" | "PM";
} => {
	const hour = parseInt(time.split(":")[0]);
	let displayHour = hour;
	const period = hour >= 12 ? "PM" : "AM";

	if (hour > 12) {
		displayHour = hour - 12;
	} else if (hour === 0) {
		displayHour = 12;
	}

	return { hour: displayHour, period };
};

interface MeetingTimeFieldProps {
	startTime: HourMinuteString;
	endTime: HourMinuteString;
	setStartTime: Dispatch<SetStateAction<HourMinuteString>>;
	setEndTime: Dispatch<SetStateAction<HourMinuteString>>;
}

export const MeetingTimeField = ({
	startTime,
	endTime,
	setStartTime,
	setEndTime,
}: MeetingTimeFieldProps) => {
	const { hour: initialStartHour, period: initialStartPeriod } =
		parseHourMinuteString(startTime);
	const { hour: initialEndHour, period: initialEndPeriod } =
		parseHourMinuteString(endTime);

	const [startHour, setStartHour] = useState(initialStartHour);
	const [startPeriod, setStartPeriod] = useState<"AM" | "PM">(
		initialStartPeriod,
	);
	const [endHour, setEndHour] = useState(initialEndHour);
	const [endPeriod, setEndPeriod] = useState<"AM" | "PM">(initialEndPeriod);

	const handleStartHourChange = (value: string) => {
		const hour = parseInt(value);
		setStartHour(hour);
		setStartTime(
			`${convertTo24Hour(hour, startPeriod)}:00:00` as HourMinuteString,
		);
	};

	const handleStartPeriodChange = (value: string) => {
		setStartPeriod(value as "AM" | "PM");
		setStartTime(
			`${convertTo24Hour(startHour, value)}:00:00` as HourMinuteString,
		);
	};

	const handleEndHourChange = (value: string) => {
		const hour = parseInt(value);
		setEndHour(hour);
		setEndTime(`${convertTo24Hour(hour, endPeriod)}:00:00` as HourMinuteString);
	};

	const handleEndPeriodChange = (value: string) => {
		setEndPeriod(value as "AM" | "PM");
		setEndTime(`${convertTo24Hour(endHour, value)}:00:00` as HourMinuteString);
	};

	return (
		<div>
			<div className="flex flex-row items-center space-x-2 text-slate-medium">
				<ClockIcon />
				<p className="text-sm font-semibold uppercase tracking-wide">
					ANY TIME BETWEEN (PST)
				</p>
			</div>

			<div className="flex w-full flex-row items-center space-x-4 pt-2 text-sm text-gray-500">
				<div className="flex gap-2">
					<Select
						value={String(startHour)}
						onValueChange={handleStartHourChange}
					>
						<SelectTrigger className="w-fit">
							<SelectValue placeholder={startHour} />
						</SelectTrigger>
						<SelectContent>
							{Array.from({ length: 12 }, (_, i) => `${i + 1}`).map((hour) => (
								<SelectItem key={hour} value={hour}>
									{hour}
								</SelectItem>
							))}
						</SelectContent>
					</Select>

					<Select value={startPeriod} onValueChange={handleStartPeriodChange}>
						<SelectTrigger className="w-fit">
							<SelectValue placeholder={"AM"} />
						</SelectTrigger>
						<SelectContent>
							<SelectItem value="AM">AM</SelectItem>
							<SelectItem value="PM">PM</SelectItem>
						</SelectContent>
					</Select>
				</div>

				<span> and </span>

				<div className="flex gap-2">
					<Select value={String(endHour)} onValueChange={handleEndHourChange}>
						<SelectTrigger className="w-fit">
							<SelectValue placeholder={endHour} />
						</SelectTrigger>
						<SelectContent>
							{Array.from({ length: 12 }, (_, i) => `${i + 1}`).map((hour) => (
								<SelectItem key={hour} value={hour}>
									{hour}
								</SelectItem>
							))}
						</SelectContent>
					</Select>

					<Select value={endPeriod} onValueChange={handleEndPeriodChange}>
						<SelectTrigger className="w-fit">
							<SelectValue placeholder={"PM"} />
						</SelectTrigger>
						<SelectContent>
							<SelectItem value="AM">AM</SelectItem>
							<SelectItem value="PM">PM</SelectItem>
						</SelectContent>
					</Select>
				</div>
			</div>
		</div>
	);
};

// src/lib/components/creation/MeetingV2/MeetingTimeField.svelte
<script lang="ts">
  import { startTime, endTime } from "$lib/stores/meetingSetupStores";
  import type { HourMinuteString } from "$lib/types/chrono";
  import { cn } from "$lib/utils/utils";
  import ClockIcon from "~icons/material-symbols/nest-clock-farsight-analog-outline";

  let startHour: number = 9;
  let endHour: number = 4;
  let startPeriod: "AM" | "PM" = "AM";
  let endPeriod: "AM" | "PM" = "PM";

  const convertTo24Hour = (hour: number, period: "AM" | "PM"): string => {
    if (period === "PM" && hour !== 12) {
      hour += 12;
    } else if (period === "AM" && hour === 12) {
      hour = 0;
    }

    return hour.toString().padStart(2, "0");
  };

  $: $startTime = `${convertTo24Hour(startHour, startPeriod)}:00` as HourMinuteString;
  $: $endTime = `${convertTo24Hour(endHour, endPeriod)}:00` as HourMinuteString;
</script>

<div>
  <div class="flex flex-row items-center gap-x-1 pb-2 text-slate-medium">
    <ClockIcon />
    <p class="text-sm font-semibold uppercase tracking-wide">ANY TIME BETWEEN (PST)</p>
  </div>

  <div
    id="meeting-time-input-container"
    class="flex flex-col flex-wrap gap-x-2 space-y-2 pt-2 text-sm text-gray-500 xs:flex-row xs:items-center xs:space-y-0 xs:pt-0 md:gap-x-4"
  >
    <div class="flex gap-[6px]">
      <select bind:value={startHour} class="select select-bordered h-8 min-h-0 py-0 pl-3 pr-8">
        {#each Array.from({ length: 12 }, (_, i) => i + 1) as hour}
          <option value={hour} selected={startHour === hour}>{hour}</option>
        {/each}
      </select>
      <select bind:value={startPeriod} class="select select-bordered h-8 min-h-0 py-0 pl-3 pr-8">
        <option selected={startPeriod === "AM"}>AM</option>
        <option selected={startPeriod === "PM"}>PM</option>
      </select>
    </div>

    <span class="pl-2 xs:pl-0"> and </span>

    <div class="flex gap-[6px]">
      <select
        bind:value={endHour}
        class={cn(
          "select select-bordered h-8 min-h-0 py-0 pl-3 pr-8",
          $startTime >= $endTime && "border-red-500 focus:border-red-500 focus:outline-red-500",
        )}
      >
        {#each Array.from({ length: 12 }, (_, i) => i + 1) as hour}
          <option value={hour} selected={endHour === hour}>{hour}</option>
        {/each}
      </select>
      <select
        bind:value={endPeriod}
        class={cn(
          "select select-bordered h-8 min-h-0 py-0 pl-3 pr-8",
          $startTime >= $endTime && "border-red-500 focus:border-red-500 focus:outline-red-500",
        )}
      >
        <option selected={endPeriod === "AM"}>AM</option>
        <option selected={endPeriod === "PM"}>PM</option>
      </select>
    </div>
  </div>
</div>
